sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '7'
env:
- EMBER_VERSION=default
matrix:
  fast_finish: true
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set spin false
- npm install -g npm@^2
install:
- mkdir travis-phantomjs
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
- export PATH=$PWD/travis-phantomjs:$PATH
- npm install merge
- npm install broccoli-merge-trees
- npm install -g bower
- npm install
- bower install
- ./scripts/update-dependencies
- ./scripts/build-static -f -s
script:
- echo "done installing"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YHPhuPyQt6L0aVuP0uex3y3PrApjaPcSsrdhY/FUz/e0yi49qpd0mHHcZfAhju1LNBE4Pavo4QjL09CSRPw7QFsDKtC860zlBFwEhK14Zwc8R47YI/Y3dRYoZaa7QSf+elImsEJ2kW5AqSZDW+50hg2jCVM7mpADSe116NLDZleoKWlJ4D+Gkj0y8K2YnBkL141I/BDVUJ5oosbVbBKGTDtcPOuP8mO1FniGYvOFunO+NkRBVXWmwj0TQMNkch6HIENcayomyGdb5rdYn56CEJMBsQ+XQfRXOkhcWcj93CHEMsE4jNqzAZLQQp3oN7kYgpz1HjHUuM+zxQVsuA0oTofBJwCrFKmMcB/9udELMLGePurfPgSahGFCHTVNMdR9GbvNOkjXwDCexYKYunYLLd98bhYi20NuwPbxwfjFopHf8UHsKKBjGEvC625IYogR+aw+o5N6/fQmFSBwlQT0GeEAnCIw5fKNU8Q3RFaFrjtT98qDohFs3b6aaJ2EjuO2dVHCsnst8rpeka3M6N0v6BNWVxnstH21dAZ0PrGzW2KngFt55pUeDNysXufL+gzwNydbAOGjAnfD7LXUOLAEiB2liSx9mqt6VroEijfKTANuJh5OVIXamZ2Lf6UDBzDpXK5h+4fP//dw7NyEL3NEcqOs/79CMROXUgJwjlT0yvU=
  file: ./dist/static/1.6.4.tar.gz
  on:
    tags: true
    repo: Cerfoglg/ui
